name: firebase_auth_app
description: A new Flutter project using Firebase Authentication and Firestore
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0

  # Utility packages
  fluttertoast: ^8.2.5
  http: ^1.2.1

  # Other dependencies (if needed in your project)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
